services:
  web:
    build: ./
    command: nodemon -L ./bin/www
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  frontend:
    build: ./frontend
    command: npm start
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/usr/src/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true